### PR TITLE
Prepare variants for better board manage

### PR DESCRIPTION
**Pull request by petrkr**
This PR introduce variants folder and include this folder in platformio.ini

That will make easier managing of existing and new boards. Also if someone add own board to platformio.ini and you will make changes, it will NOT conflict after this change, because it will be untracked new folder inside variants folder, so any changes to other boards (like now ePaper ones) will NOT cause conflicts during rebase to latest master

In next step is move all boards from platformio.ini to variants, but for now this is minimum to make possible to do for new boards. Old ones can be moved momentary.

There are lot of boards, so it will take lot of work to move them all. But since it is include not change, then it can be done one-by-one but not need to at once..

I will show in next PR example with moved few boards.

### CODE REVIEW

**Comment by richonguzman** [comment]
so a variants folder will be created to mange all the future boards?

meshtastic kind of doing things ?

**Comment by petrkr** [comment]
Yes, not only meshtastic, I saw it at other platformio projects too and it is kind of good idea I think. Especially if you want add boards and you do not want anytime solve conflicts in one huge platformio.ini

**Comment by petrkr** [comment]
Here is commit with moved boards to variants folder

https://github.com/petrkr/LoRa_APRS_iGate/commit/c266a254cc1ad8208b74946c5bf2e2fa1cce7003

**Comment by petrkr** [comment]
Rebased to latest master. Due adding of NTP library I had to do it again, because it again conflicts. 

Btw I added NTP Client too few weeks ago to ethernet version :) So it will conflict me too.. But your implementation is better. I just turned on NTP Client and not did anything longer, as had no time now

**Comment by richonguzman** [comment]
So, I need to talk to you on Telegram to understand a few things about this variants (which is really awesome idea to get this right and be easy to add more and more boards as they come)

also need some help with a little ntp bug I found

**Comment by richonguzman** [comment]
this seems to be implemented

**Pull request closed without merging**
