### PR TITLE
Web configurator and more

### PR DESCRIPTION
**Pull request by SQ2CPA**
- web configurator available at board IP (via DHCP or auto AP static IP)
- auto AP (automatic access point) that turns if no WiFi is available
- simple installer, you don't need platformio
- github workflow for building and packing fw for each board with installer
- added initial support for heltec ht-ct62

I hope the changes are useful, 73! SQ2CPA

### CODE REVIEW

**Comment by richonguzman** [comment]
excelente! lets go

**Review by richonguzman — COMMENTED** [review]
go

**Review by richonguzman — APPROVED** [review]
now

**Comment by dc1rdb** [comment]
Great enhancement!
On the web configurator page (at board IP), would it be possible to add a link to the OTA update page (board IP/update)?
73 de Robert

**Comment by richonguzman** [comment]
will add to the TODO list ;)

**Pull request merged**
