### PR TITLE
Prepare Arduino 3.x support

### PR DESCRIPTION
**Pull request by petrkr**
This will update libraries and replace deprecated functions regarding to new libraries

### CODE REVIEW

**Comment by petrkr** [comment]
Any progress in this PR?

**Comment by petrkr** [comment]
Rebased to latest main.

How it looks ?

**Comment by petrkr** [comment]
Rebased to latest main... How looks this PR ? It block me from make PCB with SPI ethernet.

**Comment by petrkr** [comment]
Rebased to latest master also updated library versions to the latest

**Comment by petrkr** [comment]
Rebased to last master.

**Comment by richonguzman** [comment]
all of this implemented!

**Pull request closed without merging**
