### PR TITLE
Adding support for LOLIN ESP32 DevKit with built-in OLED

### PR DESCRIPTION
**Pull request by kerk1v**
Hello, 

I've added support for the LOLIN ESP32 DevKit with Built-in 0,96" OLED Display. 

- Pin definitions for Lora Module (I used AIThinker R-02 with SX1278) 
- Pin definitions for built-in OLED. 

Tested, AP and WiFi connections work, LoRa module connects to ESP32 DevKit, Conection to APRS-IS works, Web config interface is functional. 

Still waiting for my GPS Lilygo Module to be delivered and no other LoRa trackers nearby, so LoRa part not finally tested.

### CODE REVIEW

**Comment by richonguzman** [comment]
Hi,! great !!!!

should I wait for the LoRa validation on your side?

**Comment by kerk1v** [comment]
> Hi,! great !!!!
> 
> should I wait for the LoRa validation on your side?

It's fine, I have tested it with another ESP32, your Tracker FW and the second LoRa module and all is well, so merge if you don't see other issues. 

Thanks for the great job with these firmwares!

**Comment by kerk1v** [comment]
Hi, 

Tested after my Tracker arrived, all works well. Merge away, if you wish

**Comment by richonguzman** [comment]
i will merge this in the future days ;) thanks a lot

**Pull request closed without merging**
