### PR TITLE
Added AlwaysOn Checks for Screen

### PR DESCRIPTION
**Pull request by czajkaej**
When AlwaysOn is false, screen now shuts off to conserve power. Good for Solar Digi nodes. - KI6PSP

### CODE REVIEW

**Comment by richonguzman** [comment]
hi,

so this will make the screen completely turn off when switch is enabled for this.

but the time  for momentary turn on does control  it independently ?

**Comment by czajkaej** [comment]
Yes, it shuts off the screen completely. Trying to save power for a solar
build by shutting off the screen.

Ed (KI6PSP)

**Comment by richonguzman** [comment]
> Yes, it shuts off the screen completely. Trying to save power for a solar build by shutting off the screen. Ed (KI6PSP)
> 

(I'm on the phone but very curious). but does this work only on the time It should wait (when is False) before turning off

or does it replace que other mode from before?

I was thinking of 3 modes:
full off
full on
on for x secs then off

**Comment by czajkaej** [comment]
I was thinking about this too. These are the 3 modes I think are needed.
1. Always On
2. Sometimes On - Notifications Only
3. Never On - Solar build

This current implementation is like mode 3, it’s only on at startup, then
shuts off.

This current build doesn’t do #2, but maybe we can work together on this?

https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEimKylNrCmpJFQpfomK3smmfAcWtpfPHEvTOC9cH5xhWOz5Wo2oAL13uKwfIHVmQYAZoCN2VNwMxZEXuppivKN3-GuQ-sgVABM6zp6UFSykF7Nfjm5wjD6OWZb6jiH8tclvcySgWYa91KNvt_NrQPkr_pyUQA5ycES1OyyKXNtMyBjmLXeTDow9_XCJCvc/s4032/image_6209779.JPG
https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEimKylNrCmpJFQpfomK3smmfAcWtpfPHEvTOC9cH5xhWOz5Wo2oAL13uKwfIHVmQYAZoCN2VNwMxZEXuppivKN3-GuQ-sgVABM6zp6UFSykF7Nfjm5wjD6OWZb6jiH8tclvcySgWYa91KNvt_NrQPkr_pyUQA5ycES1OyyKXNtMyBjmLXeTDow9_XCJCvc/s320/image_6209779.JPG
This is what I am experimenting with. A solar powered Digi I can put on a
hill. Also, I got this one to push telemetry that APRS.FI <http://aprs.fi/> can
graph.
https://aprs.fi/telemetry/a/KI6PSP-4

**Comment by richonguzman** [comment]
i will close this PR but still have this idea running around to see how to adde better use of the screen

thanks for pointing this out

**Pull request closed without merging**
